# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOF8vqoTefpBomigeW1Y-qNlsvYYnih5
"""

!pip install streamlit

import streamlit as st
import joblib
import re

# ==============================
# LOAD MODEL
# ==============================
model = joblib.load('model.pkl')
vectorizer = joblib.load('vectorizer.pkl')

# ==============================
# CLEAN FUNCTION
# ==============================
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text

# ==============================
# PAGE CONFIG
# ==============================
st.set_page_config(
    page_title="Language Detector",
    page_icon="🌍",
    layout="centered"
)

# ==============================
# HEADER
# ==============================
st.title("🌍 Language Detection App")
st.markdown("Detect the language of any text instantly using Machine Learning.")

# ==============================
# SIDEBAR
# ==============================
st.sidebar.header("ℹ️ About")
st.sidebar.write("""
- Model: Linear SVM
- Features: Character TF-IDF
- Supports multiple languages
""")

st.sidebar.markdown("---")
st.sidebar.write("Built with ❤️ using Streamlit")

# ==============================
# INPUT SECTION
# ==============================
st.subheader("✍️ Enter Text")

user_input = st.text_area(
    "Type or paste text here:",
    height=150,
    placeholder="Example: Bonjour tout le monde"
)

# Example buttons
st.markdown("**Try examples:**")
col1, col2, col3 = st.columns(3)

with col1:
    if st.button("English"):
        user_input = "Hello, how are you?"

with col2:
    if st.button("French"):
        user_input = "Bonjour tout le monde"

with col3:
    if st.button("Spanish"):
        user_input = "Hola, cómo estás?"

# ==============================
# PREDICTION
# ==============================
if st.button("🚀 Detect Language"):

    if user_input.strip() == "":
        st.warning("⚠️ Please enter some text.")

    elif len(user_input.strip()) < 3:
        st.warning("⚠️ Text too short to detect language.")

    else:
        cleaned = clean_text(user_input)
        transformed = vectorizer.transform([cleaned])

        prediction = model.predict(transformed)
        decision = model.decision_function(transformed)

        confidence = max(decision[0])

        # Result
        st.success(f"🌐 Predicted Language: **{prediction[0]}**")

        # Confidence bar
        st.progress(min(abs(confidence)/5, 1.0))
        st.caption(f"Confidence Score: {confidence:.2f}")

# ==============================
# FOOTER
# ==============================
st.markdown("---")
st.caption("🚀 Deployed ML App | Built for Portfolio")